name: Cloud Run Deploy

on:
  workflow_call:
    inputs:
      name:
        description: 'Domain name of deployment, before `.demo.community.intersystems.com`'
        required: true
        type: string
    secrets:
      SERVICE_ACCOUNT_KEY:
        required: true
  workflow_dispatch:
    inputs:
      repository:
        description: 'Deploying repository'
        required: true
        type: string
      ref:
        description: 'Branch Name in deploying repository'
        required: true
        type: choice
        default: main
        options:
          - master
          - main
      name:
        description: 'Domain name of deployment, before `.demo.community.intersystems.com`'
        required: true
        type: string
      memory:
        description: 'Memory for the instance'
        type: string
      port:
        description: 'WebPort for the running instance'
        type: string

env:
  # Change this section according to your needs
  IMAGE_NAME:   ${{ inputs.name }}
  SERVICE:      ${{ inputs.name }}
  DOMAIN_NAME:  ${{ inputs.name }}.demo.community.intersystems.com

# Leave this section untouched
  PROJECT_ID:   iris-community-demos
  CLUSTER_NAME: demo
  GITHUB_SHA:   ${{ github.sha }}
  GCR_LOCATION: eu.gcr.io
  REGION:       europe-west2
  NAMESPACE:    demo
  SERVICE_PORT: ${{ inputs.port }}
  SERVICE_MEMORY: ${{ inputs.memory }}

jobs:
  deploy-cloud-run:
    # if: github.event.repository.fork == false && github.event.repository.is_template == false
    name: Deploy to Cloud Run
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}

    - name: Google Authentication
      uses: google-github-actions/auth@v1.0.0
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1.0.1
      with:
        project_id:   ${{ env.PROJECT_ID }}
        cluster_name: ${{ env.CLUSTER_NAME }}
        location:     ${{ env.REGION }}

    - name: Setup gcloud cli
      uses: google-github-actions/setup-gcloud@v1.0.0
      with:
        version: '412.0.0'

    - name: Authorize Docker push
      run: |
        gcloud auth list
        gcloud --quiet auth configure-docker

    - name: Build and Push image
      run: |
        docker buildx build -t ${GCR_LOCATION}/${PROJECT_ID}/${IMAGE_NAME}:${GITHUB_SHA} --push .

    - name: Deploy to Cloud Run
      run: |
        echo "[INFO] Set google project..."
        gcloud config set project ${PROJECT_ID}

        echo "[INFO] Deploy service..."
        gcloud run deploy ${SERVICE}         \
          --platform gke                     \
          --cluster ${CLUSTER_NAME}          \
          --cluster-location ${REGION}       \
          --namespace ${NAMESPACE}           \
          --port ${SERVICE_PORT:-52773}      \
          --min-instances 1                  \
          --memory ${SERVICE_MEMORY:-512Mi}  \
          --timeout 300                      \
          --verbosity debug                  \
          --image ${GCR_LOCATION}/${PROJECT_ID}/${IMAGE_NAME}:${GITHUB_SHA}

        echo "[INFO] Create domain mappings..."
        if [[ $(gcloud run domain-mappings list --platform gke --cluster ${CLUSTER_NAME} --cluster-location ${REGION} --namespace ${NAMESPACE} --filter "DOMAIN=${DOMAIN_NAME}" | grep -v DOMAIN | wc -l) == 0 ]]; then
          gcloud run domain-mappings create \
            --service ${SERVICE}            \
            --platform gke                  \
            --cluster ${CLUSTER_NAME}       \
            --cluster-location ${REGION}    \
            --namespace ${NAMESPACE}        \
            --verbosity debug               \
            --domain ${DOMAIN_NAME}
        fi

    - name: Create domain name
      run: |
        kubectl version
        echo "[INFO] Checking if [${DOMAIN_NAME}] is in the existing Ingress annotation..."
        CURRENT_DOMAINS_LIST=$(kubectl -n gke-system get svc istio-ingress -o jsonpath="{.metadata.annotations['external-dns\.alpha\.kubernetes\.io/hostname']}")
        if [[ $(echo ${CURRENT_DOMAINS_LIST} | grep -w "${DOMAIN_NAME}" | wc -c) -eq 0 ]]; then \
          echo "[INFO] Domain [${DOMAIN_NAME}] is ABSENT in the domains list. Adding...";       \
          kubectl -n gke-system annotate --overwrite svc istio-ingress external-dns\.alpha\.kubernetes\.io/hostname=${CURRENT_DOMAINS_LIST},${DOMAIN_NAME}; \
          echo -n "[INFO] Resulting domain names: "
          kubectl -n gke-system get svc istio-ingress -o jsonpath="{.metadata.annotations['external-dns\.alpha\.kubernetes\.io/hostname']}"
        else
          echo "[INFO] Domain [${DOMAIN_NAME}] is in the domains list. Leave untouched...";     \
        fi

    - name: Enable TLS-access
      run: |
        kubectl version
        kubectl patch configmap config-domainmapping -n knative-serving -p '{"data":{"autoTLS":"Enabled"}}'
